# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Run tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx10240m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'verify'
- task: PublishBuildArtifacts@1
  displayName: 'Publish results'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/jmeter/results'
    ArtifactName: 'JMeter results'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: 'Publish logs'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target/jmeter/logs'
    ArtifactName: 'JMeter logs'
    publishLocation: 'Container'